services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: todo
    networks:
      - app-net

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-net

networks:
  app-net:

volumes:
  mysql_data:
